### ISSUE TITLE
Create a usability test report based on the feedback you gathered from #6

### ISSUE THREAD

**Issue by Ultarius** [Ultarius/FedoraGame#12]
Current usability test report: https://docs.google.com/document/d/11WhpK-U83MdtI1DiLA9Zi7DxoaY-56umUX21jNQWnog/edit

**Comment by Wiejeben** [comment]
https://docs.google.com/document/d/11WhpK-U83MdtI1DiLA9Zi7DxoaY-56umUX21jNQWnog/edit

**Comment by Wiejeben** [comment]
Add description to test persons
