### ISSUE TITLE
Perform a usability test together with the current game manual and game rules

### ISSUE THREAD

**Issue by Ultarius** [Ultarius/FedoraGame#6]

**Comment by ghost** [comment]
taken:
1. het killen van een tegenstander is essentieel, geen idee waarom dit een taak was.
2. na 20 minuten bereikt door Hielke.
3. er was geen reden om een archer meer range te geven. de range tiles waren te ver uit de weg.
4. niemand ging voor de winning tiles, te veel moeite.
5. iedereen ging voor de ACOV aangezien die automatisch verkregen was.
6. niemand ging voor de winning tiles aangezien ze geen voorbeeld gaven.
7. het bord werd gebruikt voor uitleg en werd niet opgeruimd.
