### ISSUE TITLE
Define clearly the interactions between the game elements in a document

### ISSUE THREAD

**Issue by Ultarius** [Ultarius/FedoraGame#8]
Current rulebook: https://docs.google.com/document/d/11g-FcNaG_ZtXApFizE10IYaYmpyRoC7nSjTDeKWLFYw/edit

**Comment by Wiejeben** [comment]
Maarten concept: https://docs.google.com/document/d/1y4DuIHFVdJaKKhvTlinf_Vn8B_UZxUmsknPSl9reI2M/edit#

**Comment by Wiejeben** [comment]
Rulebook (=game elements) must be simplified: Game elements must be specified.
